In [1]:
!ls

01_imitation.pdf imitations.ipynb main.py          training.py
data             imitations.py    network.py


In [11]:
import os
import numpy as np
import gym
from pyglet.window import key

In [12]:
def load_imitations(data_folder):
    """
    1.1 a)
    Given the folder containing the expert imitations, the data gets loaded and
    stored it in two lists: observations and actions.
                    N = number of (observation, action) - pairs
    data_folder:    python string, the path to the folder containing the
                    observation_%05d.npy and action_%05d.npy files
    return:
    observations:   python list of N numpy.ndarrays of size (96, 96, 3)
    actions:        python list of N numpy.ndarrays of size 3
    """
    observations = []
    actions = []
    
    # List all files in the data folder
    files = sorted(os.listdir(data_folder))
    
    for file in files:
        # Check if the file is an observation or action file
        if file.startswith("observation_"):
            obs_path = os.path.join(data_folder, file)
            observations.append(np.load(obs_path))
        elif file.startswith("action_"):
            action_path = os.path.join(data_folder, file)
            actions.append(np.load(action_path))
    
    return observations, actions

In [13]:
def test_load_imitations():
    data_folder = './data/teacher'  
    observations, actions = load_imitations(data_folder)
    print(observations[0].shape)
    # Print the first 5 observations and actions to check the outcome
    for i in range(len(actions)):
        #print(f"Observation {i+1}:", observations[i])
        print(f"Action {i+1}:", actions[i])

test_load_imitations()

(96, 96, 3)
Observation 1: [[[102 204 102]
  [102 204 102]
  [102 204 102]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[102 204 102]
  [102 204 102]
  [102 204 102]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[102 204 102]
  [102 204 102]
  [102 204 102]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 ...

 [[102 204 102]
  [102 204 102]
  [102 204 102]
  ...
  [102 204 102]
  [102 204 102]
  [102 204 102]]

 [[102 204 102]
  [102 204 102]
  [102 204 102]
  ...
  [102 204 102]
  [102 204 102]
  [102 204 102]]

 [[102 204 102]
  [102 204 102]
  [102 204 102]
  ...
  [102 204 102]
  [102 204 102]
  [102 204 102]]]
Action 1: [0. 0. 0.]
